services:
  wireguard:
    image: opensmart/wireguard
    container_name: opensmart-wireguard
    hostname: wireguard
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    environment:
      - SERVER_IP=${SERVER_IP:-SERVER_IP}
    volumes:
      - ./volumes/data:/data
    ports:
      - "51820:51820/udp"
    networks:
      - opensmart
    restart: unless-stopped

networks:
  opensmart:
    external: true
    name: opensmart
